#!/bin/sh

#---------------------------{
# place gdi files
if [ "`pwd`" = "/usr/bin" ]; then
	export	PATH1="/usr/share/gdi"
else
	export	PATH1="`pwd`/data"
fi
#---------------------------}


# Checking root
if [[ $EUID -ne 0 ]]; then
	. "$PATH1"/WarningRoot
fi


# Create folder idf not exist.
if [ -d /tmp/gdi ]
then
	echo "Info: File /tmp/gdi exist."
	rm -fvr /tmp/gdi
	mkdir /tmp/gdi
else
	mkdir /tmp/gdi
	echo "Info: File /tmp/gdi created."
fi


# Path to /tmp/gdi
export TMPDIR=/tmp/"$(basename $0)"


# Load all functions from "functions" file
. "$PATH1/functions"


# Load Buttons status
FuncButtonsActivity


funcRefreshAllBall() {
	echo '	<action function="refresh">BallAfterStep</action>
		<action function="refresh">BallCinnamon</action>
		<action function="refresh">BallEnlightenment</action>
		<action function="refresh">BallFluxbox</action>
		<action function="refresh">BallFVWM</action>
		<action function="refresh">BallIceWM</action>
		<action function="refresh">BallKde</action>
		<action function="refresh">BallLxde</action>
		<action function="refresh">BallMate</action>
		<action function="refresh">BallOpenbox</action>
		<action function="refresh">BallWindowMaker</action>
		<action function="refresh">BallXfce</action>	'
}


GTKDIALOG=gtkdialog

export MAIN_DIALOG='
<window title="GDI">
	<vbox>

		<frame>
			<hbox>
				<pixmap space-expand ="true">
					<input file>'"$PATH1"'/icons/gdi/gdi.png</input>
        		</pixmap>

			<vseparator height-request="10"></vseparator>

				<vbox>
					<hbox>
						<pixmap>
							<input file>'"$PATH1"'/icons/gdi/green_ball.png</input>
        				</pixmap>
						<text>
							<label>"- Green ball means desktop environment is installed."</label>
						</text>
					</hbox>
					<hbox>
						<pixmap>
							<input file>'"$PATH1"'/icons/gdi/red_ball.png</input>
        				</pixmap>
						<text>
							<label>"- Red ball means desktop environment is uninstalled."</label>
						</text>
					</hbox>
				</vbox>
			</hbox>
		</frame>

		<frame Status:>

			<vbox scrollable="true" width-request="450" width="525" height="300">

				<hbox homogeneous="true">
					<text xalign="0">
						<label>"AfterStep"</label>
					</text>
					<hbox>
						<pixmap>
							<input file>'"$TMPDIR"'/StateBallAfterStep.png</input>
							<variable>BallAfterStep</variable>
        				</pixmap>
						<button>
							<label>Install / Uninstall</label>
							<variable>AfterStepInstall</variable>
							<input file icon="bottom"></input>
							<action>echo "You pressed button AfterStep Install"</action>
							<action>GRAPHIC=AfterStep; echo -e "$GRAPHIC" > /tmp/gdi/action</action>
							<action>FuncWarningAsk</action>
							'"`funcRefreshAllBall`"'
						</button>
						<button>
							<label>Screenshot</label>
							<action>echo "You pressed screenshot button."</action>
							<action>SCREENSHOT=afterstep.png ; echo "$SCREENSHOT" > /tmp/gdi/screenshot</action>
							<action>. '"$PATH1"'/WindowScreenshots</action>
						</button>
					</hbox>
				</hbox>

			<hseparator width-request="100"></hseparator>

				<hbox homogeneous="true">
					<text>
						<label>Cinnamon</label>
					</text>
					<hbox>
						<pixmap>
							<input file>'"$TMPDIR"'/StateBallCinnamon.png</input>
							<variable>BallCinnamon</variable>
        				</pixmap>
						<button>
							<label>Install / Uninstall</label>
							<variable>CinnamonInstall</variable>
							<input file icon="bottom"></input>
							<action>echo "You pressed button Cinnamon Install"</action>
							<action>GRAPHIC=Cinnamon; echo -e "$GRAPHIC" > /tmp/gdi/action</action>
							<action>FuncWarningAsk</action>
							'"`funcRefreshAllBall`"'
						</button>
						<button>
							<label>Screenshot</label>
							<action>echo "You pressed screenshot button."</action>
							<action>SCREENSHOT=cinammon.png ; echo "$SCREENSHOT" > /tmp/gdi/screenshot</action>
							<action>. '"$PATH1"'/WindowScreenshots</action>
						</button>
					</hbox>
				</hbox>

			<hseparator width-request="100"></hseparator>

				<hbox homogeneous="true">
					<text>
						<label>Enlightenment</label>
					</text>
						<hbox>
							<pixmap>
								<input file>'"$TMPDIR"'/StateBallEnlightenment.png</input>
								<variable>BallEnlightenment</variable>
        					</pixmap>
							<button>
								<label>Install / Uninstall</label>
								<variable>EnlightenmentInstall</variable>
								<input file icon="bottom"></input>
								<action>echo "You pressed button Enlightenment Install"</action>
								<action>GRAPHIC=Enlightenment; echo -e "$GRAPHIC" > /tmp/gdi/action</action>
								<action>FuncWarningAsk</action>
								'"`funcRefreshAllBall`"'
							</button>
							<button>
								<label>Screenshot</label>
								<action>echo "You pressed screenshot button."</action>
								<action>SCREENSHOT=e19.png ; echo "$SCREENSHOT" > /tmp/gdi/screenshot</action>
								<action>. '"$PATH1"'/WindowScreenshots</action>
							</button>
						</hbox>
				</hbox>

			<hseparator width-request="100"></hseparator>

				<hbox homogeneous="true">
					<text>
						<label>Fluxbox</label>
					</text>
						<hbox>
							<pixmap>
								<input file>'"$TMPDIR"'/StateBallFluxbox.png</input>
								<variable>BallFluxbox</variable>
        					</pixmap>
							<button>
								<label>Install / Uninstall</label>
								<variable>FluxboxInstall</variable>
								<input file icon="bottom"></input>
								<action>echo "You pressed button Fluxbox Install"</action>
								<action>GRAPHIC=Fluxbox; echo -e "$GRAPHIC" > /tmp/gdi/action</action>
								<action>FuncWarningAsk</action>
								'"`funcRefreshAllBall`"'
							</button>
							<button>
								<label>Screenshot</label>
								<action>echo "You pressed screenshot button."</action>
								<action>SCREENSHOT=fluxbox.png ; echo "$SCREENSHOT" > /tmp/gdi/screenshot</action>
								<action>. '"$PATH1"'/WindowScreenshots</action>
							</button>
						</hbox>
				</hbox>

			<hseparator width-request="100"></hseparator>

				<hbox homogeneous="true">
					<text>
						<label>FVWM</label>
					</text>
						<hbox>
							<pixmap>
								<input file>'"$TMPDIR"'/StateBallFVWM.png</input>
								<variable>BallFVWM</variable>
        					</pixmap>
							<button>
								<label>Install / Uninstall</label>
								<variable>FVWMInstall</variable>
								<input file icon="bottom"></input>
								<action>echo "You pressed button FVWM Install"</action>
								<action>GRAPHIC=FVWM; echo -e "$GRAPHIC" > /tmp/gdi/action</action>
								<action>FuncWarningAsk</action>
								'"`funcRefreshAllBall`"'
							</button>
							<button>
								<label>Screenshot</label>
								<action>echo "You pressed screenshot button."</action>
								<action>SCREENSHOT=fvwm2.png ; echo "$SCREENSHOT" > /tmp/gdi/screenshot</action>
								<action>. '"$PATH1"'/WindowScreenshots</action>
							</button>
						</hbox>
				</hbox>

			<hseparator width-request="100"></hseparator>

				<hbox homogeneous="true">
					<text>
						<label>IceWM</label>
					</text>
						<hbox>
							<pixmap>
								<input file>'"$TMPDIR"'/StateBallIceWM.png</input>
								<variable>BallIceWM</variable>
        					</pixmap>
							<button>
								<label>Install / Uninstall</label>
								<variable>IceWMInstall</variable>
								<input file icon="bottom"></input>
								<action>echo "You pressed button IceWM Install"</action>
								<action>GRAPHIC=IceWM; echo -e "$GRAPHIC" > /tmp/gdi/action</action>
								<action>FuncWarningAsk</action>
								'"`funcRefreshAllBall`"'
							</button>
							<button>
								<label>Screenshot</label>
								<action>echo "You pressed screenshot button."</action>
								<action>SCREENSHOT=icewm.png ; echo "$SCREENSHOT" > /tmp/gdi/screenshot</action>
								<action>. '"$PATH1"'/WindowScreenshots</action>
							</button>
						</hbox>
				</hbox>

			<hseparator width-request="100"></hseparator>

				<hbox homogeneous="true">
					<text>
						<label>KDE4  </label>
					</text>
						<hbox>
							<pixmap>
								<input file>'"$TMPDIR"'/StateBallKde.png</input>
								<variable>BallKde</variable>
        					</pixmap>
							<button>
								<label>Install / Uninstall</label>
								<variable>KdeInstall</variable>
								<input file icon="bottom"></input>
								<action>echo "You pressed button Kde Install"</action>
								<action>GRAPHIC=Kde; echo -e "$GRAPHIC" > /tmp/gdi/action</action>
								<action>FuncWarningAsk</action>
								'"`funcRefreshAllBall`"'
							</button>
							<button>
								<label>Screenshot</label>
								<action>echo "You pressed screenshot button."</action>
								<action>SCREENSHOT=kde.png ; echo "$SCREENSHOT" > /tmp/gdi/screenshot</action>
								<action>. '"$PATH1"'/WindowScreenshots</action>
							</button>
						</hbox>
				</hbox>

			<hseparator width-request="100"></hseparator>

				<hbox  homogeneous="true">
					<text>
						<label>LXDE  </label>
					</text>
						<hbox>
							<pixmap>
								<input file>'"$TMPDIR"'/StateBallLxde.png</input>
								<variable>BallLxde</variable>
        					</pixmap>
							<button>
								<label>Install / Uninstall</label>
								<variable>LxdeInstall</variable>
								<input file icon="bottom"></input>
								<action>echo "You pressed button Lxde Install."</action>
								<action>GRAPHIC=Lxde; echo -e "$GRAPHIC" > /tmp/gdi/action</action>
								<action>FuncWarningAsk</action>
							'"`funcRefreshAllBall`"'
							</button>
							<button>
								<label>Screenshot</label>
								<action>echo "You pressed screenshot button."</action>
								<action>SCREENSHOT=lxde.png ; echo "$SCREENSHOT" > /tmp/gdi/screenshot</action>
								<action>. '"$PATH1"'/WindowScreenshots</action>
							</button>
						</hbox>
				</hbox>

			<hseparator width-request="100"></hseparator>

				<hbox  homogeneous="true">
					<text>
						<label>MATE  </label>
					</text>
						<hbox>
							<pixmap>
								<input file>'"$TMPDIR"'/StateBallMate.png</input>
								<variable>BallMate</variable>
        					</pixmap>
							<button>
								<label>Install / Uninstall</label>
								<variable>MateInstall</variable>
								<input file icon="bottom"></input>
								<action>echo "You pressed button Mate Install"</action>
								<action>GRAPHIC=Mate; echo -e "$GRAPHIC" > /tmp/gdi/action</action>
								<action>FuncWarningAsk</action>
								'"`funcRefreshAllBall`"'
							</button>
							<button>
								<label>Screenshot</label>
								<action>echo "You pressed screenshot button."</action>
								<action>SCREENSHOT=mate.png ; echo "$SCREENSHOT" > /tmp/gdi/screenshot</action>
								<action>. '"$PATH1"'/WindowScreenshots</action>
							</button>
						</hbox>
				</hbox>

			<hseparator width-request="100"></hseparator>

				<hbox  homogeneous="true">
					<text>
						<label>Openbox  </label>
					</text>
						<hbox>
							<pixmap>
								<input file>'"$TMPDIR"'/StateBallOpenbox.png</input>
								<variable>BallOpenbox</variable>
        					</pixmap>
							<button>
								<label>Install / Uninstall</label>
								<variable>OpenboxInstall</variable>
								<input file icon="bottom"></input>
								<action>echo "You pressed button Openbox Install"</action>
								<action>GRAPHIC=Openbox; echo -e "$GRAPHIC" > /tmp/gdi/action</action>
								<action>FuncWarningAsk</action>
								'"`funcRefreshAllBall`"'
							</button>
							<button>
								<label>Screenshot</label>
								<action>echo "You pressed screenshot button."</action>
								<action>SCREENSHOT=openbox.png ; echo "$SCREENSHOT" > /tmp/gdi/screenshot</action>
								<action>. '"$PATH1"'/WindowScreenshots</action>
							</button>
						</hbox>
				</hbox>

			<hseparator width-request="100"></hseparator>

				<hbox  homogeneous="true">
					<text>
						<label>WindowMaker  </label>
					</text>
						<hbox>
							<pixmap>
								<input file>'"$TMPDIR"'/StateBallWindowMaker.png</input>
								<variable>BallWindowMaker</variable>
        					</pixmap>
							<button>
								<label>Install / Uninstall</label>
								<variable>WindowMakerInstall</variable>
								<input file icon="bottom"></input>
								<action>echo "You pressed button WindowMaker Install"</action>
								<action>GRAPHIC=WindowMaker; echo -e "$GRAPHIC" > /tmp/gdi/action</action>
								<action>FuncWarningAsk</action>
								'"`funcRefreshAllBall`"'
							</button>
							<button>
								<label>Screenshot</label>
								<action>echo "You pressed screenshot button."</action>
								<action>SCREENSHOT=windowmaker.png ; echo "$SCREENSHOT" > /tmp/gdi/screenshot</action>
								<action>. '"$PATH1"'/WindowScreenshots</action>
							</button>
						</hbox>
				</hbox>

			<hseparator width-request="100"></hseparator>

				<hbox  homogeneous="true">
					<text>
						<label>XFCE4</label>
					</text>
						<hbox>
							<pixmap>
								<input file>'"$TMPDIR"'/StateBallXfce.png</input>
								<variable>BallXfce</variable>
        					</pixmap>
							<button>
								<label>Install / Uninstall</label>
								<variable>XfceInstall</variable>
								<input file icon="bottom"></input>
								<action>echo "You pressed button Xfce Install"</action>
								<action>GRAPHIC=Xfce; echo -e "$GRAPHIC" > /tmp/gdi/action</action>
								<action>FuncWarningAsk</action>
								'"`funcRefreshAllBall`"'
							</button>
							<button>
								<label>Screenshot</label>
								<action>echo "You pressed screenshot button."</action>
								<action>SCREENSHOT=xfce.png ; echo "$SCREENSHOT" > /tmp/gdi/screenshot</action>
								<action>. '"$PATH1"'/WindowScreenshots</action>
							</button>
						</hbox>
				</hbox>

			</vbox>

		</frame>

			<hbox>
				<button space-fill="true">
					<input file>'"$PATH1"'/icons/gdi/test1.png</input>
					<action>echo "You pressed GDI button"</action>
					<action>. '"$PATH1"'/WindowAbout</action>
				</button>
				<button>
					<label>Exit</label>
					<input file icon="exit"></input>
					<action>echo You pressed exit button</action>
					<action type="exit">Exit by button</action>
				</button>
			</hbox>

	</vbox>
</window>
'

gtkdialog -c  --program MAIN_DIALOG
echo "Program has finished"

#
#



