#! /bin/sh


export WarningAsk='
<window title="WarningAsk" icon-name="gtk-dialog-warning">


<vbox> 
	<frame>

		<hbox>
			<pixmap icon_size="6">
				<input file stock="gtk-dialog-warning"></input>
			</pixmap>

				<vbox>
					<text>
						<label>'"$ASK"'</label>
					</text>
				</vbox>
		</hbox>

	</frame>

		<hbox>
			<button yes>
				<variable>warningaskwindow</variable>
				<action>echo "You pressed Yes button."</action>



				<action>ln -fsn "'$PATH1'/'${BALL}'.png" "/tmp/gdi/StateBall'${GRAPHIC}'.png"</action>
				<action type="closewindow">"warningaskwindow"</action>
			</button>


				<button no>
			</button>
		</hbox>
</vbox> 
</window>  
'
	gtkdialog -c  --program WarningAsk
