#!/bin/sh



funcList1() {

# count lines
CountLines=$(cat `pwd`/data/list/${GRAPHIC}.list | wc -l)
arch=`arch`


# For 32 bit and 64 bit Support :-)
if [[ "$arch" == "x86_64" ]]; then
	# 64 bit system
	cat `pwd`/data/list/${GRAPHIC}.list > /tmp/gdi/packages.list
else
	# for example 32 bit system
	cat `pwd`/data/list/${GRAPHIC}.list | sed 's/lib64/lib/' > /tmp/gdi/packages.list
fi



funcList2() {
	for i in `seq 1 $CountLines`
	do
			#line from lista_elf
			ab=$(awk 'NR=='$i `pwd`/data/list/${GRAPHIC}.list)

			echo '	<checkbox>
						<label>'$ab'</label>
						<default>true</default>
						<action>echo Odznaczyłeś '$ab' .</action>
						<action>if true echo "'$ab'" >> /tmp/gdi/packages.list</action> 
						<action>if false echo "$(cat /tmp/gdi/packages.list | grep -v "'$ab'")" > /tmp/gdi/packages.list</action> 
						<action>echo "======="</action> 
						<action>cat /tmp/gdi/packages.list</action> 
					</checkbox>'
	done
}

#if echo "$WORK" | grep -q "Uninstall"; then
if [[ "$WORK" == "Uninstall" ]]; then


echo '			<text>
					<label>You can check which packages will removed</label>
				</text>
				<text>
					<label>and you can unmark, if you need have:</label>
				</text>

			<expander expanded="false" use-underline="true">
				<vbox scrollable="true" width-request="220" width="250" height="300">


				'"`funcList2`"'
				</vbox>
			<label>Click to show list:</label>
			</expander>
'


elif [[ "$WORK" == "Install" ]]; then

			echo '<hseparator width-request="100"></hseparator>'
else
		echo '<text>
			<label>Error funcList</label>
		</text>'

fi

}





export WarningAsk='
<window title="WarningAsk" icon-name="gtk-dialog-warning">


<vbox> 
	<frame>

		<hbox>
			<pixmap icon_size="6">
				<input file stock="gtk-dialog-warning"></input>
			</pixmap>

				<vbox>
					<text>
						<label>'"$ASK"'</label>
					</text>
				</vbox>
		</hbox>

				'"`funcList1`"'

	</frame>

		<hbox>
			<button yes>
				<variable>warningaskwindow</variable>
				<action>echo "You pressed Yes button."</action>
				<action>echo "1" > '"$TMPDIR"'/action</action>
				<action type="closewindow">"warningaskwindow"</action>
			</button>


			<button no>
				<action>echo "0" > '"$TMPDIR"'/action</action>
				<action>echo "tablica: ${tablica2[*]}"</action>
				<action type="closewindow">"warningaskwindow"</action>

			</button>
		</hbox>

</vbox> 
</window>  
'
	gtkdialog -c  --program WarningAsk





