#!/bin/sh





funcList() {


lista="/home/gg/PRACE/GTKDIALOG/Gdi15/gdi/data/list/Mate.list"

# count lines
CountLines=$(cat `pwd`/list/Mate.list | wc -l)



	for i in `seq 1 $CountLines`
	do
		#line from lista_elf
		ab=$(awk 'NR=='$i `pwd`/list/Mate.list)


		echo '	<checkbox>
					<label>'$ab'</label>
					<default>true</default>
					<action>echo Odznaczyłeś '$ab' , zapisz do pliku i potem wykorzystaj grep albo usuń z tablicy pakietów.</action>

     			 </checkbox>'
	done

}




export WindowAbout='
<window title="About GDI"  window-position="1"	modal="true" resizable="false">
	<vbox>

		<text>
			<label>You can check which packages will removed</label>
		</text>
		<text>
			<label>and you can unmark, if you need have:</label>
		</text>

		<expander expanded="false" use-underline="true">


			<vbox scrollable="true" width-request="220" width="250" height="300">


				'"`funcList`"'


			</vbox>
			<label>Click to show list:</label>
		</expander>

		<hbox space-expand="false" space-fill="false">
			<button use-stock="true" label="gtk-ok" width-request="90">
				<action>closewindow:winAbout</action>
			</button>
		</hbox>
	</vbox>
	<variable export="false">winAbout</variable>
</window>
'
gtkdialog -c  --program WindowAbout








