#!/bin/bash


SCREEN=$(cat /tmp/gdi/screenshot)
echo ""$PATH1"/screenshots/"$SCREEN""

FILE=""$PATH1"/links/$(echo $SCREEN | sed 's/.png/.link/')"
echo "File: $FILE"

LINK="$(cat $FILE)"
echo "$LINK"




export WindowAbout='

<vbox>

	<frame>
		<pixmap>
			<input file>"'"$PATH1"'/screenshots/'"$SCREEN"'"</input>
		</pixmap>
	</frame>

	<hbox  homogeneous="true">
		<pixmap>
			<input file>"'"$PATH1"'/icons/desktop/x32/'"$SCREEN"'"</input>
		</pixmap>
		<text>
    		<label>"'"$SCREEN"'"</label>
		</text>
		<button>
			<label>'$"Link to website."'</label>
			<action>funcURLOpen "'$LINK'"</action>
		</button>
		<button ok></button>
	</hbox>
</vbox>


'
gtkdialog -c  --program WindowAbout
